### PR TITLE
Shameless self promotion of report.ci

### PR DESCRIPTION
**Pull request by klemens-morgenstern**
Heya, I built a tool (report.ci) to report test results as a github check_run, as can be seen here: https://github.com/report-ci/dogen/runs/90723037

I've set this up for this project, in case you're intersted.

### CODE REVIEW

**Comment by mcraveiro** [comment]
Hi mate,

just sent you a couple of emails on this subject and now I finally saw the PR :-) cool I'll merge it. I assume the changes do not impact the CDash upload? I saw the builds coming through in CDash so it looks all good.

**Comment by mcraveiro** [comment]
OK merged. However, the badge is blank at present and when I click on it, it takes me to:

https://report.ci/status/MASD-Project/dogen?branch=master

and I get:

```
{"error":"Installation not found"}
```
I assume you are doing some changes. I'll keep an eye and report back.

Cheers

**Comment by klemens-morgenstern** [comment]
Nope, you need to install the app to your github repository, so report.ci has access rights. You can do that here: https://github.com/apps/report-ci/installations/new

**Comment by mcraveiro** [comment]
Aha. Cool, OK done that I think, but now when I click on the badge it takes me to:

https://github.com/organizations/report-ci/settings/apps/report-ci/installations

And I get a 404 there...

**Comment by klemens-morgenstern** [comment]
Right, that'll work once you commit the first test data. Will change the code to tell you that.

After that it will forward you to the newest check_run on github.

**Comment by mcraveiro** [comment]
Ah I see. So basically when the first build is finished sort of thing. For some reason I only have one travis-ci agent today and its doing OSX so it may take a while. I'll report back in an hour or so.

**Comment by klemens-morgenstern** [comment]
Awesome, thanks for testing. 

Btw. if you want to report the build status from CDash you can do that as well (though that will require a token) using the [scheduling scripts](https://report.ci/scheduling).

**Comment by mcraveiro** [comment]
> Awesome, thanks for testing.

No problems, got to help fellow product developers! :-)

> Btw. if you want to report the build status from CDash you can do that as well (though that will require a token) using the [scheduling scripts](https://report.ci/scheduling).

Cool, I'll backlog that, it would be useful actually.

**Comment by mcraveiro** [comment]
OK travis is looking pretty weird today, OSX timed out and now nothing is happening for some reason :-( on the plus side, windows completed and it looks *great*! :-)

https://github.com/MASD-Project/dogen/runs/90790856

A few suggestions/comments - bit of a random brain dump, so take it with a big grain of salt! :-D

- what is ```Windows $env:compiler $env:configuration```? seems like something is not quite right with the build name.
- it would be great to have a tree like view of the tests, so that you could drill into test suites.
- it would be great to have a timing view of tests, a la CDash [test time graph](https://my.cdash.org/testDetails.php?test=46007899&build=1630254). However, CDash only shows the test time. It would be better if you could see the overall time it took to run a) all tests b) a test suite or c) an individual test. Most of the time I just care about the test suites tbh.
- CDash aslo tells you when tests slow down.

All I can think of for now, if I have any more ideas I'll ping you. At any rate, congrats, its looking good already! :-)

**Comment by klemens-morgenstern** [comment]
Ok, so it does work (https://github.com/MASD-Project/dogen/runs/90790856) but it seems I screwed up the variable substitution, because I am not using powershell for the python script execution. That means that the test runs overwrite each other. I would normally create a PR, but given how much that clogs up your build pipes I'd rather not.

**Comment by mcraveiro** [comment]
Eh eh, yeh build system seems to be a bit crazy today! :-) but don't worry, if you need it for testing go for it, I'll tidy -up as required at my end.

**Comment by mcraveiro** [comment]
Ah, actually another half-baked thought: if somehow you could "merge" the build matrix with the tests suites, that would be great :-D I mean this is a bit crazy and I haven't thought it through, but I normally don't really care about an individual platform, unless it is failing lots of tests. More important would be to have an overall view of all platforms:

```
-> All tests for all test suites
   -> test suites
       -> tests
           -> platforms
```

Or actually, maybe that is not accurate: what I mean is, when things are green I rather have this breakdown in a test tree. When things are red, then platforms tend to be more important. So basically, what I am saying in a complicated way is that maybe there are several useful views over the test set...

**Comment by klemens-morgenstern** [comment]
Do you want passing reports to not be visible or test results to be merged? I have not support for the latter yet

**Comment by mcraveiro** [comment]
No, what I mean is, I think your overview report is really good but it may need like several "levels". One of which is the "merged" or "overall" report. When things go red, then you want to look at the detail sort of thing.

**Comment by mcraveiro** [comment]
Maybe this will make more sense when I see the other platforms. At present it seems CDash has gone green on a few platforms:

https://my.cdash.org/index.php?project=MASD+Project+-+Dogen

How can I see these in report-ci?

**Comment by klemens-morgenstern** [comment]
Ah, well if I wouldn't have screwd up the naming on appveyor, you would already see the different results. If they have the same name, the prior test will be overwritten. It should look like this:

https://github.com/report-ci/boost-example/runs/84457866

**Comment by mcraveiro** [comment]
Ah ok cool, well that looks cool. Hopefully I'll get to see the Dogen version for OSX and Linux, these should not be overwritten right?

**Comment by klemens-morgenstern** [comment]
They should not, but they didn't receive any test data yet, so there's nothing to see. 
Btw. you can also parse compiler output if you want even more annotations, but there seem to be other issues going on in your build.

**Comment by mcraveiro** [comment]
Ah, I get it, the runs are coming under the report-ci fork of Dogen!

https://github.com/report-ci/dogen/runs/90780849

Well, I guess it makes sense, it is your commits into report-ci/Dogen that are causing these builds.

**Pull request merged**
